module.exports = `

    scalar Date
    type Item { 
        name: String,
        path: String,
        dateCreate: Date,
        size: Float,
        itFolder: Boolean
    }

    type Query {
        items (folder: String): [Item],
        rootFolders: [Item]
    }

`;
