module.exports = `

    scalar Date
    type Item { 
        name: String,
        path: String,
        dateCreate: Date,
        size: Float,
        itFolder: Boolean
    }

    type Query {
        items (folder: String): [Item],
        rootFolders: [Item]
    }

    type Mutation {
        createFolder(folder: String, name: String): Item,
        renameItem(file: String, name: String): Item,
        copyItems(files: [String], folder: String): [Item],
        moveItems(files: [String], folder: String): [Item],
        deleteItem(file: String): Item,
    }

`;
