module.exports = `

    scalar Date
    type Item { 
        id: Int,
        title: String, 
        img: String,
        itemType: String,
        orderNumber: Int,
        owner: String,
        description: String,
        myPrice: Int,
        myPriceHot: Int,
        active: Boolean,
        priceList: [Price],
        urlList: [Url],
        minPrice: [Price] 
    }

    type Price {
        id: Int,
        date: Date,
        price: Float,
        itemId: Int,
        itemUrl: Url    
    }

    type Url {
        id: Int,
        itMain: Boolean,
        url: String,
        itemId: Int,
        domain: String,
        discount: Int   
    }

    type Query {
        items (itemType: String, limit: Int, offset: Int, id: Int): [Item]
        item (id: Int): Item
        itemPrices (itemId: Int, date: Date, price: Float): [Price]
        itemUrls (itemId: Int): [Url]
    }
    type Mutation {
        item (
            id: Int,
            title: String, 
            img: String,
            itemType: String,
            orderNumber: Int,
            owner: String,
            description: String,
            myPrice: Int,
            myPriceHot: Int,
            active: Boolean 
        ): Item
        itemPrice (
            id: Int,
            date: Date,
            price: Float,
            itemId: Int,
            itemUrlId: Int
        ): Price,
        itemUrl (
            id: Int,
            itMain: Boolean,
            url: String,
            itemId: Int,
            discount: Int
        ): Url
    }
`;
