export default {
    ROOT_REQUEST: 'ROOT_REQUEST',
    ROOT_RECEIVE: ' ROOT_RECEIVE',
    ITEMS_REQUEST: 'ITEMS_REQUEST',
    ITEMS_RECEIVE: 'ITEMS_RECEIVE',
    GO_ROOT: 'GO_ROOT',
    FOLDER_CREATE: 'FOLDER_CREATE',
    ITEM_RENAME: 'ITEM_RENAME'
};
